### ISSUE TITLE
Description under title title

### ISSUE THREAD

**Issue by lfarah** [google/cocoapods-size#2]
Please add a description under the title.
<img width="395" alt="screen shot 2018-08-23 at 10 18 20" src="https://user-images.githubusercontent.com/6511079/44527651-de18d800-a6bd-11e8-955e-ce46f901d4e0.png">

 My idea is:
```Measure the final binary size of a CocoaPods library.```

**Comment by VinayGuthal** [comment]
Thanks for raising :)
Updated to
Measure the final binary size for the given set of Cocoapods (since the tool helps in measuring the size of a combination of cocoapods as well)
