### ISSUE TITLE
ARCHIVE FAILED when using Xcode 10.2

### ISSUE THREAD

**Issue by davidair** [google/cocoapods-size#9]
When using Xcode 10.2, the tool fails with ARCHIVE FAILED:

```
./measure_cocoapod_size.py --cocoapods FirebaseAnalytics
```

Build system information
error: An empty identity is not valid when signing a binary for the product type 'Application'. (in target 'SizeTest')

** ARCHIVE FAILED **

**Comment by gmoraleda** [comment]
Same here.

**Comment by dsringari** [comment]
Bumping this +1

**Comment by gmoraleda** [comment]
Found the solution.
The `size_build_configuration.json` file needs to include the location of your project and the flag `CODE_SIGNING_ALLOWED` needs to be set to `NO`. In my case:

```
{
  "projectFile": "/{path-to}/cocoapods-size/sizetestproject/SizeTest.xcodeproj",
  "appScheme": "SizeTest",
  "iOSVersion": "8.0",
  "compilerFlags": {
    "ARCHS": "arm64",
    "CODE_SIGN_IDENTITY": "",
    "CODE_SIGNING_REQUIRED": "NO",
    "CODE_SIGNING_ALLOWED": "NO",
    "ENABLE_BITCODE": "NO"
  },
  "withLinkMap": true,
  "officialData": false
}
```

With these two changes I'm able to run the project and get Cocoapod sizes. ✌️

**Comment by VinayGuthal** [comment]
Looking into this

**Comment by VinayGuthal** [comment]
Thanks a lot gmoraleda for looking into this issue! https://github.com/google/cocoapods-size/pull/10 should fix the issue thanks :+1:

**Comment by VinayGuthal** [comment]
Fixed by gmoraleda
